### ISSUE TITLE
Update REAMDE

### ISSUE THREAD

**Issue by ADI10HERO** [Auto-DL/Deployment-Flask#3]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Deployment-Flask/issues) or a new implementation?
NO

### Feature Description
Filling TOODs in readme

**Comment by ADI10HERO** [comment]
@Onkar302 Can you please take up this issue?

**Comment by Onkar302** [comment]
Ok, will take it up after I am done a bit on unit testing.
